In [1]:
import pandas as pd
import numpy as np
import collections

In [2]:
dictionary={
    'Name':['Jack','Amit','Harry','Saka'],
    'Age':[22,34,33,28],
    'Striker':['True','False','False','True']
}

In [3]:
ds=pd.DataFrame(data=dictionary)
ds

    Name  Age Striker
0   Jack   22    True
1   Amit   34   False
2  Harry   33   False
3   Saka   28    True

In [4]:
ds['Gender']=['Male','Male','Male','Male']
ds

    Name  Age Striker Gender
0   Jack   22    True   Male
1   Amit   34   False   Male
2  Harry   33   False   Male
3   Saka   28    True   Male

In [5]:
df=pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
#slicing
df.iloc[1:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [7]:
#based on condition
df[df['Sex'] == 'female'].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [8]:
#sort
df.sort_values(by=['Age']).head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C

In [9]:
df['Sex']=df['Sex'].replace(['female','male'],['Woman','Man'])
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Man,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,38.0,1,0,PC 17599,71.2833,C85,C

In [10]:
#Rename
df.rename(columns={'Pclass': 'Passenger Class'}).head(2)

,PassengerId,Survived,Passenger Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Man,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,38.0,1,0,PC 17599,71.2833,C85,C

In [11]:
#old col with names as a key and empty strings as value
col_nam=collections.defaultdict(str)
for name in df.columns:
    col_nam[name]
col_nam

defaultdict(str,
            {'PassengerId': '',
             'Survived': '',
             'Pclass': '',
             'Name': '',
             'Sex': '',
             'Age': '',
             'SibSp': '',
             'Parch': '',
             'Ticket': '',
             'Fare': '',
             'Cabin': '',
             'Embarked': ''})

In [12]:
#min,amx,mean,count,sum
print('1',df['Age'].max())
print('2',df['Age'].min())
print('3',df['Age'].mean())
#print('4',df['Age'].avg())
print('5',df['Age'].sum())
print('6',df['Age'].count())

1 80.0
2 0.42
3 29.69911764705882
5 21205.17
6 714

In [13]:
print(df['Sex'].unique())
print(df['Sex'].value_counts())

['Man' 'Woman']
Sex
Man      577
Woman    314
Name: count, dtype: int64

In [14]:
# handling missing values
print(df[df['Age'].isnull()].head())

    PassengerId  Survived  Pclass                           Name    Sex  Age  \
5             6         0       3               Moran, Mr. James    Man  NaN
17           18         1       2   Williams, Mr. Charles Eugene    Man  NaN
19           20         1       3        Masselmani, Mrs. Fatima  Woman  NaN
26           27         0       3        Emir, Mr. Farred Chehab    Man  NaN
28           29         1       3  O'Dwyer, Miss. Ellen "Nellie"  Woman  NaN

    SibSp  Parch  Ticket     Fare Cabin Embarked
5       0      0  330877   8.4583   NaN        Q
17      0      0  244373  13.0000   NaN        S
19      0      0    2649   7.2250   NaN        C
26      0      0    2631   7.2250   NaN        C
28      0      0  330959   7.8792   NaN        Q

In [15]:
print(df[df['Age'].isna()].head(2))

    PassengerId  Survived  Pclass                          Name  Sex  Age  \
5             6         0       3              Moran, Mr. James  Man  NaN
17           18         1       2  Williams, Mr. Charles Eugene  Man  NaN

    SibSp  Parch  Ticket     Fare Cabin Embarked
5       0      0  330877   8.4583   NaN        Q
17      0      0  244373  13.0000   NaN        S

In [16]:
#drop the column
df.drop('Age',axis=1).head(2)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Man,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,1,0,PC 17599,71.2833,C85,C

In [17]:
#if you want to delete multiple column
df.drop(['Age','Sex'],axis=1).head(2)

,PassengerId,Survived,Pclass,Name,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,PC 17599,71.2833,C85,C

In [18]:
#if column doesnot have name
df.drop(df.columns[1],axis=1).head(2)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",Man,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,38.0,1,0,PC 17599,71.2833,C85,C

In [19]:
#deleting a rows

In [20]:
df[df['Sex'] != 'Man'].head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Woman,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Woman,35.0,1,0,113803,53.1000,C123,S

In [21]:
df[df['Name']!='Alison,Miss Helen Lorain'].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Man,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,38.0,1,0,PC 17599,71.2833,C85,C

In [22]:
# delete a specific record
df[df.index != 1].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Man,22.0,1,0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",Woman,26.0,0,0,STON/O2. 3101282,7.925,NaN,S

In [23]:
#drop duplicates
df.drop_duplicates().head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Man,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,38.0,1,0,PC 17599,71.2833,C85,C

In [24]:
print(f'number of rows in org dataframe{len(df)}')
print(f'number of rows after duplicates remove:{len(df.drop_duplicates())}')

number of rows in org dataframe891
number of rows after duplicates remove:891

In [25]:
df.drop_duplicates(subset=['Sex'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Man,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,38.0,1,0,PC 17599,71.2833,C85,C

In [26]:
# using keep method
df.drop_duplicates(subset=['Sex'],keep='last')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Woman,NaN,1,2,W./C. 6607,23.45,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",Man,32.0,0,0,370376,7.75,NaN,Q

In [27]:
# to check a row is duplicate or not
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [28]:
#Grop by method in Python

In [29]:
#Gropping rows by values
df.groupby('Sex').mean(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
Man,454.147314,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893
Woman,431.028662,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818

In [30]:
df.groupby('Sex')# nothing return something because it need to paired some operation like mean,median,sum

In [31]:
df.groupby('Survived')['Name'].count()

Survived
0    549
1    342
Name: Name, dtype: int64

In [32]:
df.groupby(['Survived','Sex'])['Age'].mean()

Survived  Sex
0         Man      31.618056
          Woman    25.046875
1         Man      27.276022
          Woman    28.847716
Name: Age, dtype: float64

In [33]:
# grouping rows by time
time_index=pd.date_range('06/06/2017',periods=100000,freq='30S')

C:\Users\Admin\AppData\Local\Temp\ipykernel_11216\1149855202.py:2: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  time_index=pd.date_range('06/06/2017',periods=100000,freq='30S')

In [34]:
ds=pd.DataFrame(index=time_index)

In [35]:
ds['Sale_Amount']=np.random.randint(1,10,100000)

In [36]:
ds.resample('W').sum()#group by rows per week

            Sale_Amount
2017-06-11        86411
2017-06-18       100892
2017-06-25       100668
2017-07-02       100810
2017-07-09       101085
2017-07-16        10450

In [37]:
ds.resample('2W').mean()

            Sale_Amount
2017-06-11     5.000637
2017-06-25     4.999008
2017-07-09     5.007316
2017-07-23     5.024038

In [38]:
# aggregating operations and stastics

In [39]:
df.agg({"Age":["mean"],"Survived":["count"]})

             Age  Survived
mean   29.699118       NaN
count        NaN     891.0

In [40]:
ds.agg('min')

Sale_Amount    1
dtype: int32