In [11]:
import pandas as pd
import numpy as np
import collections

In [2]:
dictionary={
    'Name':['Jack','Amit','Harry','Saka'],
    'Age':[22,34,33,28],
    'Striker':['True','False','False','True']
}

In [3]:
ds=pd.DataFrame(data=dictionary)
ds

    Name  Age Striker
0   Jack   22    True
1   Amit   34   False
2  Harry   33   False
3   Saka   28    True

In [4]:
ds['Gender']=['Male','Male','Male','Male']
ds

    Name  Age Striker Gender
0   Jack   22    True   Male
1   Amit   34   False   Male
2  Harry   33   False   Male
3   Saka   28    True   Male

In [5]:
df=pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
#slicing
df.iloc[1:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [7]:
#based on condition
df[df['Sex'] == 'female'].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [8]:
#sort
df.sort_values(by=['Age']).head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C

In [9]:
df['Sex']=df['Sex'].replace(['female','male'],['Woman','Man'])
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Man,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,38.0,1,0,PC 17599,71.2833,C85,C

In [10]:
#Rename
df.rename(columns={'Pclass': 'Passenger Class'}).head(2)

,PassengerId,Survived,Passenger Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Man,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Woman,38.0,1,0,PC 17599,71.2833,C85,C

In [13]:
#old col with names as a key and empty strings as value
col_nam=collections.defaultdict(str)
for name in df.columns:
    col_nam[name]
col_nam

defaultdict(str,
            {'PassengerId': '',
             'Survived': '',
             'Pclass': '',
             'Name': '',
             'Sex': '',
             'Age': '',
             'SibSp': '',
             'Parch': '',
             'Ticket': '',
             'Fare': '',
             'Cabin': '',
             'Embarked': ''})

In [18]:
#min,amx,mean,count,sum
print('1',df['Age'].max())
print('2',df['Age'].min())
print('3',df['Age'].mean())
#print('4',df['Age'].avg())
print('5',df['Age'].sum())
print('6',df['Age'].count())

1 80.0
2 0.42
3 29.69911764705882
5 21205.17
6 714

In [20]:
print(df['Sex'].unique())
print(df['Sex'].value_counts())

['Man' 'Woman']
Sex
Man      577
Woman    314
Name: count, dtype: int64